### ISSUE TITLE
Performance Tests

### ISSUE THREAD

**Issue by bobanco** [chadselph/akka-smpp#3]
Hi Chad Selph, 

It's really good to see SMPP implementation on a top of akka streams, 
Have you ever did performance comparison between this implementation and cloudhopper.smpp which is based on Netty and how it performs? 

Looking to hear your opinion. 

Regards.

**Comment by chadselph** [comment]
Sorry I didn't see this earlier.

I haven't done a comparison. I would be pretty surprised if cloudhopper wasn't a lot faster. But it's not so simple to compare, as they're both just libraries, not full ESMEs/SMSCs. In the real world, your SMPP server will probably be bounded by the windowing speed anyway, which is bound by whatever process you do before ack'ing submit_sm/deliver_sm (i.e. persist to disk, forward to another service, etc.)
